#!/usr/bin/env bash
# Tool Name :- Amazer-Tracer
# Author :- Shantanu Shivam 
# Date :- 28/02/2024

case "$1" in
  -m)
    php .tracem.php
  ;;
  -t)
    case "$#" in
    2)
      php .traceip.php $2
    ;;
    *)
      echo "error : invalid arguments !!"
      echo "use: ip-tracer -t <target_ip>"
    ;;
    esac
  ;;
  -u)
    php .update.php
    exit
  ;;
  update)
    php .update.php
    exit
  ;;
  start)
    php .IP-Tracer.php
    exit
  ;;
  -rm)
    php .uninstall.php
    exit
  ;;
  *)
    echo "Usage: ip-tracer [command]... [arguments]..."
    echo " Commands:"
    echo " -t <target_ip>      to trace target ip."
    echo " -m                  to trace your own ip."
    echo " -h                  to show help."
    echo " -u                  to update ip-tracer."
    echo " help                to show help."
    echo " update              to update ip-tracer."
    echo " start               to start ip-tracer menu."
esac
